#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width		3
bspc config window_gap			10

bspc config split_ratio			0.50
bspc config borderless_monocle		true
bspc config gapless_monocle		true
bspc config focus_follows_pointer	true
bspc config click_to_focus		true
bspc config top_padding			20
bspc config bottom_padding		0
bspc config right_padding		0
bspc config left_padding		0

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Firefox desktop='2'

polybar top &
