#! /bin/sh

#░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
#░█▀▄░█▀▀░█▀█░█░█░█▄█░░░█▀▀░█▀█░█▀█░█▀▀░▀█▀░█▀▀░
#░█▀▄░▀▀█░█▀▀░█▄█░█░█░░░█░░░█░█░█░█░█▀▀░░█░░█░█░
#░▀▀░░▀▀▀░▀░░░▀░▀░▀░▀░░░▀▀▀░▀▀▀░▀░▀░▀░░░▀▀▀░▀▀▀░
#░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

pgrep -x sxhkd > /dev/null || sxhkd &

#bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor -d 1 2 3 4 5
bspc monitor DP-0 -n 0 -d I
bspc monitor DP-2 -n 1 -d II
bspc monitor HDMI-0 -n 2 -d III
bspc monitor DP-4 -n 3 -d IV
bspc wm --reorder-monitors 0 1 2 3

bspc config border_width                5
bspc config window_gap                  50

bspc config split_ratio                 0.50
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config focus_follows_pointer       true
bspc config click_to_focus              true
bspc config top_padding                 25
bspc config bottom_padding              0
bspc config right_padding               0
bspc config left_padding                0
bspc config normal_border_color         $(xrdb -query | grep color0: | grep -oE '#[a-zA-Z0-9]{6}')
bspc config active_border_color         $(xrdb -query | grep color0: | grep -oE '#[a-zA-Z0-9]{6}')
bspc config focused_border_color        $(xrdb -query | grep color4: | grep -oE '#[a-zA-Z0-9]{6}')
bspc config presel_feedback_color       $(xrdb -query | grep foreground: | grep -oE '#[a-zA-Z0-9]{6}')
bspc config pointer_modifier                   mod1
bspc config pointer_motion_interval     7

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Firefox desktop='^2' follow=on state=tiled
bspc rule -a Zathura desktop='^6' follow=on state=tiled
bspc rule -a Atom desktop='^3' follow=on state=tiled
bspc rule -a TelegramDesktop desktop='^5' follow=off state=tiled

$HOME/.config/polybar/launch.sh
