#! /bin/sh

#░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
#░█▀▄░█▀▀░█▀█░█░█░█▄█░░░█▀▀░█▀█░█▀█░█▀▀░▀█▀░█▀▀░
#░█▀▄░▀▀█░█▀▀░█▄█░█░█░░░█░░░█░█░█░█░█▀▀░░█░░█░█░
#░▀▀░░▀▀▀░▀░░░▀░▀░▀░▀░░░▀▀▀░▀▀▀░▀░▀░▀░░░▀▀▀░▀▀▀░
#░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor -d 1 2 3 4 5

bspc config border_width                5
bspc config window_gap                  5 

bspc config split_ratio                 0.50
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config focus_follows_pointer       true
bspc config click_to_focus              true
bspc config top_padding                 25
bspc config bottom_padding              0
bspc config right_padding               0
bspc config left_padding                0
bspc config normal_border_color         $(xrdb -query | grep color8: | grep -oE '#[a-zA-Z0-9]{6}')
bspc config focused_border_color        $(xrdb -query | grep color4: | grep -oE '#[a-zA-Z0-9]{6}')

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Firefox desktop='^2' follow=on

$HOME/.config/polybar/launch.sh
